### ISSUE TITLE
Incorrect FEN gets printed after clicking a new computer game

### ISSUE THREAD

**Issue by PointOne1** [Panc4kes/chess.com-bot#17]
**Describe the bug**
Well I am kind of a python expert(1 year experience) so I know how things work. When I start my second bot match, things don't work right. The bot starts moving random pieces to incorrect locations(the piece cannot technically move there) and as a result, the bot fails to continue. When I check what the problem was, I was surprised! It was not the bot, but the page html that caused the issue. Basically in the 2nd bot match, instead of (class=piece wp square-22), some pieces are (class=piece square-22 wp). This is just an example of what happens to some pieces. So when you take (in get_fen.py) piece_name = piece.get_attribute("class").split()[1], the first word is not wp anymore, it is square! Further, piece_name[1].upper() the second letter here is q (s>q<uare), that's right, the piece is read as a queen instead of a pawn. I have attached a screenshot of this. This change of the position of the word doesn't appear to affect the chess pieces in chess.com, it appears to be correct. Its just that get_fen is reading it wrong. I actually also found out a working fix for this.

Replace This:
piece_name = piece.get_attribute("class").split()[1]     (LINE 13)
With This:
                if piece.get_attribute("class").split()[1][0] != "s":
                    piece_name = piece.get_attribute("class").split()[1]
                else:
                    piece_name = piece.get_attribute("class").split()[2]
                fen += piece_name[1].upper() if piece_name[0] == "w" else piece_name[1].lower()

This also doesn't cause any new bugs

**To Reproduce**
1. Go to Vs Computer in Chess.com
2. Complete first bot game
3. Play new game (without refreshing browser)

**Expected behavior**
Wrong FEN gets printed and bot fails

**Screenshots**
![image](https://user-images.githubusercontent.com/85484526/122239143-c3005e00-ced1-11eb-83ed-384b697efdec.png)

**Desktop:**
 - OS: Windows 10 Home Single Language
 - Browser Microsoft Edge
 - Version 91.0.864.48

**Comment by jsun1590** [comment]
Thanks for submitting this issue. Are you able to make a PR directly? If not I'll do one tomorrow when I've got time. Cheers!
