### ISSUE TITLE
Can u make it possible to install on linux? So not use the pywinauto libary? Thy <3

### ISSUE THREAD

**Issue by BoKa33** [Panc4kes/chess.com-bot#19]

**Comment by jsun1590** [comment]
Hi, thanks for submitting the issue! All the essential code doesn't require the pywinauto library, only for checking if the window is topmost/visible. As such, as long as you manually make the chrome window topmost, you should be able to run the script by deleting everything related to pywinauto.

However, for a Linux implementation, we could try the following (https://pywinauto.readthedocs.io/en/atspi/code/pywinauto.linux.application.html) or find a new library.

**Comment by BoKa33** [comment]
Yes, thy, I will try
